### ISSUE TITLE
Sequel adapter can't be used with setup_regexp_function: true

### ISSUE THREAD

**Issue by paddor** [digital-fabric/extralite#57]
A regexp function (for the `REGEXP` SQL operator) can't be created because `Extralite::Database#create_function` is missing:

```
Sequel::DatabaseConnectionError: NoMethodError: undefined method `create_function' for #<Extralite::Database:0x00007f5d00ae4098 :memory:>
```

PR #56 also depends on this.

**Comment by noteflakes** [comment]
This is definitely a `WONTFIX`. Due to performance and concurrency concern, Extralite does not support calling back into Ruby code while running SQLite queries. This means that you cannot define functions, aggregations, collations etc in Ruby. If you wish to do so, you'll have to use the `sqlite3-ruby` gem.

FWIW, the sqlean collection of SQLite extensions includes a [regexp extension](https://github.com/nalgeon/sqlean/blob/main/docs/regexp.md) that works great, is fast, and provides multiple functions for working with regexps.

**Comment by paddor** [comment]
No problem. But in that case I suggest removing at least these lines: https://github.com/digital-fabric/extralite/blob/main/lib/sequel/adapters/extralite.rb#L127-L131

Personally I don't use this gem yet. Given the recent improvements in Sequel  regarding Regexp caching ([shameless](https://github.com/jeremyevans/sequel/pull/2108) [plug](https://github.com/jeremyevans/sequel/pull/2116)) I just wanted to ensure drop-in compatibility with this gem.
